"""
Django settings for NGPhylogeny_fr project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))))

LOGIN_URL = '/galaxy/login'
LOGIN_REDIRECT_URL = '/'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback is only for local dev/CI - it's public (this file is on
# GitHub), so any real deployment must set NGPHYLO_SECRET_KEY instead.
SECRET_KEY = os.environ.get(
    'NGPHYLO_SECRET_KEY',
    '_m(y$t1ukdw&!z-e_)ig5h!=*#y*3db3vh81il_i=n*y24ih9k')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*", ]
INTERNAL_IPS = ["127.0.0.1", ]

# Trust a reverse proxy's X-Forwarded-Proto header to know a request was
# actually HTTPS (Django can't tell otherwise - it only sees the plain HTTP
# connection from the proxy). Inert unless that header is actually present,
# so this is safe to leave on for deployments with no proxy in front too.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CRISPY_TEMPLATE_PACK = "bootstrap3"
TESTDATA_DIR = os.path.join(BASE_DIR, 'testdata')
# Preserves pre-3.2 behavior (AutoField) instead of opting into the new
# Django 3.2 default (BigAutoField), which would alter existing PK columns.
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'formtools',
    'captcha',
    'crispy_forms',
    'account.apps.AccountConfig',
    'galaxy.apps.GalaxyConfig',
    'data.apps.DataConfig',
    'tools.apps.ToolsConfig',
    'workspace',
    'surveys.apps.SurveysConfig',
    'workflows',
    # 'workspace.apps.WorkspaceConfig',
    'blast.apps.BlastConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves STATIC_ROOT directly from the app process - needed because
    # runserver only auto-serves static files when DEBUG=True, and this
    # deployment has no separate nginx/CDN in front of it under prod
    # settings (DEBUG=False).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Must stay right after WhiteNoiseMiddleware - see
    # NGPhylogeny_fr/middleware.py's own docstring for why.
    'NGPhylogeny_fr.middleware.MaintenanceModeMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

ROOT_URLCONF = 'NGPhylogeny_fr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NGPhylogeny_fr.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
# Not CompressedManifestStaticFilesStorage: collectstatic fails hard on it
# because css/bootstrap.css references fonts/glyphicons-halflings-regular.eot,
# which was never actually included in this repo's assets - a pre-existing
# gap, not something introduced here. CompressedStaticFilesStorage still
# gzips and whitenoise-serves everything, it just doesn't hash-bust or
# validate CSS asset references.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    os.path.join(BASE_DIR, 'assets'),
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'ngphylo_cache_table',
    }
}

# Shared by local.py and prod.py so both actually get a working
# DATABASES setting - it used to live only in local.py, which meant
# prod.py (missing `from .base import *` entirely, fixed alongside
# this) had none at all.
if os.environ.get('NGPHYLO_DATABASE_HOST') is not None:
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('NGPHYLO_DATABASE_ENGINE'),
            'NAME': os.environ.get('NGPHYLO_DATABASE_NAME'),
            'USER': os.environ.get('NGPHYLO_DATABASE_USER'),
            'PASSWORD': os.environ.get('NGPHYLO_DATABASE_PASSWORD'),
            'HOST': os.environ.get('NGPHYLO_DATABASE_HOST'),
            'PORT': os.environ.get('NGPHYLO_DATABASE_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

MARKDOWN_STYLES = {'default': {
    "extras": {
        "code-friendly": None,
        "tables": None,
    },
    "safe_mode": False,  # << here's the change
}}

EMAIL_HOST = os.environ.get('NGPHYLO_EMAIL_HOST')
EMAIL_PORT = os.environ.get('NGPHYLO_EMAIL_PORT')
EMAIL_HOST_USER = os.environ.get('NGPHYLO_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('NGPHYLO_EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = (os.environ.get('NGPHYLO_EMAIL_USE_TLS')== 'True')

# See NGPhylogeny_fr/middleware.py. Case-insensitive (unlike
# EMAIL_USE_TLS's exact-'True' check above) since a maintenance toggle
# being silently wrong because someone typed "true" instead of "True" in
# a GitLab CI/CD variable has real consequences either way (site stuck up
# during an actual outage, or stuck down after maintenance ends).
NGPHYLO_MAINTENANCE_MODE = (
    os.environ.get('NGPHYLO_MAINTENANCE_MODE', '').lower() == 'true')

if EMAIL_PORT:
    # Truthy check, not "is not None": docker-compose.yml/
    # docker-compose.standalone.yml pass this through as "${NGPHYLO_EMAIL_PORT:-}",
    # which sets an empty string (not an absent var) when unconfigured -
    # int('') raises ValueError, unlike int() on a value that was never
    # set in the environment at all.
    EMAIL_PORT = int(EMAIL_PORT)
else:
    EMAIL_PORT = None

# Daily workflow-usage report (workspace.tasks.send_daily_report, scheduled
# via CELERY_BEAT_SCHEDULE below) - comma-separated recipient list. Left
# unset, the task just logs and does nothing: no report is sent, and
# nothing else is affected.
NGPHYLO_REPORT_RECIPIENTS = [
    r.strip() for r in
    os.environ.get('NGPHYLO_REPORT_RECIPIENTS', '').split(',')
    if r.strip()
]
NGPHYLO_REPORT_FROM_EMAIL = os.environ.get(
    'NGPHYLO_REPORT_FROM_EMAIL', 'ngphylogeny@pasteur.fr')

# Contact form (surveys.views.FeedbackCreateView) - comma-separated
# recipient list, same shape/empty-means-no-op convention as
# NGPHYLO_REPORT_RECIPIENTS above. Left unset, a submitted Feedback row
# is still saved to the DB as usual; no email is sent, nothing else is
# affected.
NGPHYLO_CONTACT_FORM_RECIPIENTS = [
    r.strip() for r in
    os.environ.get('NGPHYLO_CONTACT_FORM_RECIPIENTS', '').split(',')
    if r.strip()
]

# CELERY SETTINGS
#
# Celery >=4.0 also accepts the unprefixed names below (BROKER_URL,
# CELERY_DEFAULT_QUEUE, CELERY_ROUTES) via a deprecated compat shim,
# but that shim - along with celery.decorators.periodic_task, used to
# be used here - was removed in Celery 5. These are the current
# CELERY_-prefixed names, read via
# app.config_from_object('django.conf:settings', namespace='CELERY')
# in NGPhylogeny_fr/celery.py.
from celery.schedules import crontab

CELERY_BROKER_URL = os.environ.get('NGPHYLO_REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# CELERYD_CONCURRENCY = 4
CELERY_TIMEZONE = 'Europe/Madrid'
CELERY_ENABLE_UTC = True

# celery queues setup
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_ROUTES = {
    'blast.tasks.launch_ncbi_blast': {'queue': 'ncbi_blast'},
    'blast.tasks.launch_pasteur_blast': {'queue': 'default'},
    'blast.tasks.build_tree': {'queue': 'default'},
    'blast.tasks.deletegalaxyhistory': {'queue': 'default'},
    'blast.tasks.checkblastruns': {'queue': 'default'},
    'blast.tasks.deleteoldblastruns': {'queue': 'default'},
    'workspace.tasks.initializeworkspacejob': {'queue': 'default'},
    'workspace.tasks.launchmonitorworkspaces': {'queue': 'default'},
    'workspace.tasks.updateworkspacestatus': {'queue' : 'monitor'},
    'workspace.tasks.deletegalaxyhistory': {'queue': 'default'},
    'workspace.tasks.deleteoldgalaxyhistory': {'queue': 'default'},
    'workflows.tasks.deleteoldgalaxyworkflows': {'queue': 'default'},
    'workflows.tasks.deletegalaxyworkflow': {'queue': 'default'},
}

# celery beat schedule: replaces the celery.decorators.periodic_task
# decorator (removed in Celery 5) previously used directly on these
# task functions in blast/tasks.py, workflows/tasks.py and
# workspace/tasks.py. Schedules are unchanged from before.
CELERY_BEAT_SCHEDULE = {
    'blast-delete-old-runs': {
        'task': 'blast.tasks.deleteoldblastruns',
        'schedule': crontab(hour=2, minute=0),
    },
    'blast-check-runs': {
        'task': 'blast.tasks.checkblastruns',
        'schedule': crontab(),
    },
    'workflows-delete-old-galaxy-workflows': {
        'task': 'workflows.tasks.deleteoldgalaxyworkflows',
        'schedule': crontab(hour=2, minute=0),
    },
    'workspace-launch-monitor-workspaces': {
        'task': 'workspace.tasks.launchmonitorworkspaces',
        'schedule': crontab(),
    },
    'workspace-delete-old-galaxy-history': {
        'task': 'workspace.tasks.deleteoldgalaxyhistory',
        'schedule': crontab(hour=2, minute=0),
    },
    'workspace-send-daily-report': {
        'task': 'workspace.tasks.send_daily_report',
        'schedule': crontab(hour=8, minute=0),
    },
}

# Mutually exclusive by design, not just independently toggleable: once
# Pasteur's own Galaxy BLAST server is activated, prefer it exclusively
# rather than also still offering NCBI's public server (the slower, less
# controlled option - shared, rate-limited infrastructure outside this
# app's control, only bounded to a hard 10-minute timeout this session,
# see blast/tasks.py's launch_ncbi_blast). Computed once into a plain
# variable, not cross-referenced between the two dict entries below -
# Python dict literals can't self-reference like that.
_PASTEUR_BLAST_ENABLED = os.environ.get(
    'NGPHYLO_PASTEUR_BLAST_ENABLED', '').lower() == 'true'

BLASTS = {
    'pasteur' : {
        # Env-var driven (NGPHYLO_PASTEUR_BLAST_ENABLED, "true" to
        # activate - anything else/unset leaves it off, matching this
        # setting's long-standing hardcoded default), not a hardcoded
        # literal - lets this be turned on per-deployment without a code
        # change/redeploy of the setting itself, same pattern as
        # NGPHYLO_MAINTENANCE_MODE. Case-insensitive for the same reason
        # as that setting: a silently-wrong toggle here just means
        # showing/hiding a server option, not a security issue either
        # way, so being lenient about "true"/"True"/"TRUE" is worth more
        # than being strict.
        'activated' : _PASTEUR_BLAST_ENABLED,
        'name' : 'Institut Pasteur Galaxy Server',
        'progs': {
            'toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_blastn_wrapper/2.14.1+galaxy2' : {
                'name': 'blastn (nt query vs. nt db)',
                'test_data' : 'DNA_Human.fa',
                'dbs': {
                    'nt': 'Non redondant nucleotide sequence database',
                    'embl_release' : 'EMBL Release',
                    'genbank_release' : 'Genbank Release',
                    'refseqn_release' : 'RefSeq Nucleic Release',
                    'hg19' : 'hg19 complete genome',
                    'mm9' : 'mm9 complete genome',
                    'mm10' : 'mm10 complete genome',
                },
                'type' : 'blastn',
                'input': 'nt',
            },
            'toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_blastp_wrapper/2.14.1+galaxy2' : {
                'name': 'blastp (aa query vs. aa db)',
                'test_data' : 'AA_Human.fa',
                'dbs': {
                    'uniprot' : 'Uniprot',
                    'nrprot': 'Nr Prot',
                    'refseqp_release' : 'RefSeq Protein Release',
                },
                'type' : 'blastp',
                'input': 'aa',
            },
            'toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_tblastn_wrapper/2.14.1+galaxy2' : {
                'name': 'tblastn (aa query vs. nt db)',
                'test_data' : 'AA_Human.fa',
                'dbs' : {
                    'nt': 'Non redondant nucleotide sequence database',
                    'embl_release' : 'EMBL Release',
                    'genbank_release' : 'Genbank Release',
                    'refseqn_release' : 'RefSeq Nucleic Release',
                    'hg19' : 'hg19 complete genome',
                    'mm9' : 'mm9 complete genome',
                    'mm10' : 'mm10 complete genome',
                },
                'type' : 'tblastn',
                'input': 'aa',
            },
            'toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/ncbi_blastx_wrapper/2.14.1+galaxy2' : {
                'name': 'blastx (nt query vs. aa db)',
                'test_data' : 'DNA_Human.fa',
                'dbs' : {
                    'uniprot' : 'Uniprot',
                    'nrprot': 'Nr Prot',
                    'refseqp_release' : 'RefSeq Protein Release',
                },
                'type' : 'blastx',
                'input': 'nt',
            },
            # 'toolshed.pasteur.fr/repos/fmareuil/ncbi_blast_plus/ncbi_tblastx_wrapper/2.6.0' : {
            #     'name': 'tblastx (nt query vs. translated nt db)',
            #     'test_data' : 'DNA_Human.fa',
            #     'dbs' : {
            #         'nt': 'Non redondant nucleotide sequence database',
            #         'embl_release' : 'EMBL Release',
            #         'genbank_release' : 'Genbank Release',
            #         'refseqn_release' : 'RefSeq Nucleic Release',
            #         'hg19' : 'hg19 complete genome',
            #         'mm9' : 'mm9 complete genome',
            #         'mm10' : 'mm10 complete genome',
            #     },
            #     'type' : 'tblastx',
            #     'input': 'nt',
            # },
        },
    },
    'ncbi' : {
        # See _PASTEUR_BLAST_ENABLED above - mutually exclusive with
        # 'pasteur', not independently toggleable.
        'activated' : not _PASTEUR_BLAST_ENABLED,
        'name' : 'Public NCBI Blast Server',
        'progs' : {
            'blastn' : {
                'name': 'blastn (nt query vs. nt db)',
                'test_data' : 'DNA_Human.fa',
                'dbs': {
                    'nr': 'nr',
                    'refseq_genomic': 'refseq_genomic',
                    'refseq_rna': 'refseq_rna',
                },
                'type' : 'blastn',
                'input': 'nt',
            },
            'blastp' : {
                'name': 'blastp (aa query vs. aa db)',
                'test_data' : 'AA_Human.fa',
                'dbs': {
                    'refseq_protein' : 'refseq_protein',
                    'swissprot' : 'swissprot',
                },
                'type' : 'blastp',
                'input': 'aa',
            },
            'tblastn' : {
                'name': 'tblastn (aa query vs. nt db)',
                'test_data' : 'AA_Human.fa',
                'dbs' : {
                    'nr': 'nr',
                    'refseq_genomic': 'refseq_genomic',
                    'refseq_rna': 'refseq_rna',
                },
                'type' : 'tblastn',
                'input': 'aa',
            },
            'blastx' : {
                'name': 'blastx (nt query vs. aa db)',
                'test_data' : 'DNA_Human.fa',
                'dbs' : {
                    'refseq_protein' : 'refseq_protein',
                    'swissprot' : 'swissprot',
                },
                'type' : 'blastx',
                'input': 'nt',
            },
            # 'tblastx' : {
            #     'name': 'tblastx (nt query vs. translated nt db)',
            #     'test_data' : 'DNA_Human.fa',
            #     'dbs' : {
            #         'nr': 'nr',
            #         'refseq_genomic': 'refseq_genomic',
            #         'refseq_rna': 'refseq_rna',
            #     },
            #     'type' : 'tblastx',
            #     'input': 'nt',
            # },
        }
    }
}

# Launch celery workers with : (1 cpu for blast, the remaining for other tasks)
# celery multi start 2 -l INFO -c:2 1 -Q:1 default -Q:2 blast --app=NGPhylogeny_fr.celery:app
# stop them with
# celery multi stop celery1 celery2
