# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:35
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalaxyConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('anonymous_user_api_access', models.BooleanField(default=False, help_text='If True, Anonymous user must be set', verbose_name='Enable Anonymous api?')),
                ('active', models.BooleanField(default=False, verbose_name='Active Configuration?')),
            ],
        ),
        migrations.CreateModel(
            name='GalaxyServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=254, unique=True)),
                ('synopsis', models.CharField(max_length=254)),
                ('description', models.TextField(max_length=500)),
                ('contact', models.CharField(max_length=254)),
                ('version', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='GalaxyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=100)),
                ('galaxy_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.GalaxyServer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='galaxyconf',
            name='anonymous_user',
            field=models.OneToOneField(blank=True, help_text='This User is used to make Galaxy requests for NGPhylogeny Anonymous Users', null=True, on_delete=django.db.models.deletion.CASCADE, to='galaxy.GalaxyUser', verbose_name='Global Anonymous User'),
        ),
        migrations.AddField(
            model_name='galaxyconf',
            name='galaxy_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galaxy.GalaxyServer'),
        ),
        migrations.AlterUniqueTogether(
            name='galaxyuser',
            unique_together=set([('user', 'galaxy_server')]),
        ),
    ]
