# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalaxyServer',
            new_name='Server',
        ),
    ]
