# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0002_auto_20170414_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxyconf',
            name='anonymous_user',
        ),
        migrations.RemoveField(
            model_name='galaxyconf',
            name='galaxy_server',
        ),
        migrations.AddField(
            model_name='galaxyuser',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Important: User api key will be used to make all Galaxy requests for NGPhylogeny Anonymous User', verbose_name='Share this user api key with all anonymous users '),
        ),
        migrations.AddField(
            model_name='server',
            name='current',
            field=models.BooleanField(default=False, help_text='Galaxy server currently used to run jobs. Only one server can be used at the same time'),
        ),
        migrations.DeleteModel(
            name='GalaxyConf',
        ),
    ]
